# Generated by Django 4.2.9 on 2026-01-30 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_datetime', models.DateTimeField(help_text='Date and time of appointment')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='PENDING', help_text='Appointment status', max_length=20)),
                ('reason', models.TextField(help_text='Reason for visit')),
                ('notes', models.TextField(blank=True, help_text="Doctor's notes (visible only to doctor)", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(help_text='Clinic where appointment takes place', on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='clinics.clinic')),
            ],
            options={
                'db_table': 'appointments',
                'ordering': ['-appointment_datetime'],
            },
        ),
    ]
