# Generated by Django 4.2.9 on 2026-01-30 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Clinic name', max_length=200)),
                ('address', models.TextField(help_text='Street address')),
                ('city', models.CharField(help_text='City', max_length=100)),
                ('state', models.CharField(help_text='State/Province', max_length=100)),
                ('zip_code', models.CharField(help_text='Postal/ZIP code', max_length=20)),
                ('phone', models.CharField(help_text='Contact phone number', max_length=15)),
                ('email', models.EmailField(help_text='Contact email', max_length=254)),
                ('operating_hours', models.JSONField(blank=True, default=dict, help_text='Operating hours by day (JSON format)')),
                ('facilities', models.JSONField(blank=True, default=list, help_text='Available facilities (JSON array)')),
                ('description', models.TextField(blank=True, help_text='Clinic description', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is clinic currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'clinics',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['city', 'state'], name='clinics_city_dd6c17_idx'), models.Index(fields=['is_active'], name='clinics_is_acti_5ab494_idx')],
            },
        ),
    ]
