# Generated by Django 4.2.9 on 2026-01-30 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Specialization name (e.g., Cardiology, Dermatology)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the specialization', null=True)),
            ],
            options={
                'db_table': 'specializations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(help_text='Medical license number', max_length=50, unique=True)),
                ('consultation_fees', models.DecimalField(decimal_places=2, help_text='Consultation fees', max_digits=10)),
                ('biography', models.TextField(blank=True, help_text="Doctor's biography", null=True)),
                ('years_of_experience', models.PositiveIntegerField(default=0, help_text='Years of medical experience')),
                ('availability_schedule', models.JSONField(blank=True, default=dict, help_text='Weekly availability schedule (JSON format)')),
                ('is_accepting_patients', models.BooleanField(default=True, help_text='Currently accepting new patients')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(blank=True, help_text='Primary clinic', null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinics.clinic')),
                ('specialization', models.ForeignKey(help_text='Medical specialization', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctors', to='doctors.specialization')),
            ],
            options={
                'db_table': 'doctor_profiles',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
    ]
